-- ===============================================
-- CREACION DE OBJETOS DE BASE DE DATOS
-- ===============================================

-- Crear tabla de paises
CREATE TABLE countries (
    id_country NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso_code CHAR(2) UNIQUE,
    name VARCHAR2(50) UNIQUE NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de antecedentes patologicos
CREATE TABLE pathological_history (
    id_pathological_history NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    previous_surgeries VARCHAR2(100),
    allergies VARCHAR2(150),
    previous_hospitalizations VARCHAR2(150),
    accidents VARCHAR2(150)
) TABLESPACE shce_datos;

-- Crear tabla de ingredientes activos
CREATE TABLE active_ingredient (
    id_active_ingredient NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    enabled CHAR(1) DEFAULT '1' CHECK (enabled IN ('0','1')) NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de antecedentes generales
CREATE TABLE general_history (
    id_general_history NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    previous_occupations VARCHAR2(100),
    housing_material VARCHAR2(30),
    housing_ownership VARCHAR2(50),
    number_rooms NUMBER(3),
    number_inhabitants NUMBER(3),
    floor_type VARCHAR2(30),
    roof_type VARCHAR2(30),
    domestic_animals CHAR(1) CHECK (domestic_animals IN ('0','1')),
    farm_animals CHAR(1) CHECK (farm_animals IN ('0','1')),
    description_animals VARCHAR2(50),
    service_electricity CHAR(1) CHECK (service_electricity IN ('0','1')),
    service_water CHAR(1) CHECK (service_water IN ('0','1')),
    service_sewage CHAR(1) CHECK (service_sewage IN ('0','1')),
    shared_bathroom CHAR(1) CHECK (shared_bathroom IN ('0','1')),
    previous_residences VARCHAR2(100),
    previous_trips VARCHAR2(100)
) TABLESPACE shce_datos;

-- Crear tabla de antecedentes ginecologicos
CREATE TABLE gynecological_history (
    id_gynecological_history NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menarche_age NUMBER(2),
    min_catamenial_days NUMBER(2),
    max_catamenial_days NUMBER(2),
    last_menstrual_period DATE,
    gestations NUMBER(2),
    parity VARCHAR2(10),
    contraceptive_method VARCHAR2(50),
    sexual_orientation VARCHAR2(15) CHECK (sexual_orientation IN (
        'Heterosexual', 'Homosexual', 'Bisexual', 'Pansexual', 'Otro', 'Ninguno')),
    number_sexual_partners NUMBER(3)
) TABLESPACE shce_datos;

-- Crear tabla de habitos
CREATE TABLE habit (
    id_habit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(30) NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de familiares
CREATE TABLE familiar (
    id_familiar NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(30) NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de historia del paciente
CREATE TABLE patient_history (
    id_patient_history NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de enfermedades
CREATE TABLE disease (
    id_disease NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(7) NOT NULL,
    name CLOB NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de roles
CREATE TABLE roles (
    id_role NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(25) UNIQUE NOT NULL,
    enabled CHAR(1) DEFAULT '1' CHECK (enabled IN ('0','1')) NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de rutas (vías de administracion)
CREATE TABLE route (
    id_route NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abreviation VARCHAR2(10) NOT NULL,
    name VARCHAR2(50) NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de formas farmaceuticas
CREATE TABLE form (
    id_form NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(25) NOT NULL
) TABLESPACE shce_datos;

-- Crear tabla de regiones (depende de countries)
CREATE TABLE regions (
    id_region NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_country NUMBER NOT NULL,
    ubigeo CHAR(2) UNIQUE,
    name VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT fk_regions_id_country
        FOREIGN KEY (id_country)
        REFERENCES countries(id_country)
) TABLESPACE shce_datos;

-- Crear tabla de provincias (depende de regions)
CREATE TABLE provinces (
    id_province NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region NUMBER NOT NULL,
    ubigeo CHAR(2) UNIQUE,
    name VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT fk_provinces_id_region
        FOREIGN KEY (id_region)
        REFERENCES regions(id_region)
) TABLESPACE shce_datos;

-- Crear tabla de ciudades (depende de provinces)
CREATE TABLE cities (
    id_city NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_province NUMBER NOT NULL,
    ubigeo CHAR(2) UNIQUE,
    name VARCHAR2(100) UNIQUE NOT NULL,
    CONSTRAINT fk_cities_id_province
        FOREIGN KEY (id_province)
        REFERENCES provinces(id_province)
) TABLESPACE shce_datos;

-- Crear tabla de direcciones (depende de cities)
CREATE TABLE addresses (
    id_address NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_city NUMBER NOT NULL,
    street VARCHAR2(150) NOT NULL,
    reference VARCHAR2(100),
    CONSTRAINT fk_addresses_id_city
        FOREIGN KEY (id_city)
        REFERENCES cities(id_city)
) TABLESPACE shce_datos;

-- Crear tabla de areas (depende de roles)
CREATE TABLE areas (
    id_area NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_role NUMBER NOT NULL,
    name VARCHAR2(25) UNIQUE NOT NULL,
    enabled CHAR(1) DEFAULT '1' CHECK (enabled IN ('0','1')) NOT NULL,
    CONSTRAINT fk_areas_id_role
        FOREIGN KEY (id_role)
        REFERENCES roles(id_role)
) TABLESPACE shce_datos;

-- Crear tabla de presentaciones (depende de form)
CREATE TABLE presentation (
    id_presentation NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_form NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_presentation_id_form
        FOREIGN KEY (id_form)
        REFERENCES form(id_form)
) TABLESPACE shce_datos;

-- Crear tabla de pacientes
CREATE TABLE patient (
    id_patient NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_address NUMBER NOT NULL,
    id_birth_city NUMBER,
    name VARCHAR2(50) NOT NULL,
    paternal_surname VARCHAR2(25) NOT NULL,
    maternal_surname VARCHAR2(25) NOT NULL,
    document_type VARCHAR2(25) NOT NULL CHECK (document_type IN ('DNI', 'Carne de extranjeria')),
    document_number VARCHAR2(15) UNIQUE NOT NULL,
    birth_date DATE,
    age NUMBER(3),
    gender CHAR(1) NOT NULL CHECK (gender IN ('M','F')),
    ethnicity VARCHAR2(25),
    marital_status VARCHAR2(10) CHECK (marital_status IN ('Soltero','Casado','Viudo','Divorciado')),
    education_level VARCHAR2(12) CHECK (education_level IN ('Inicial','Primaria','Secundaria','Superior')),
    occupation VARCHAR2(100),
    religion VARCHAR2(20) CHECK (religion IN ('Catolico','Cristiano','Testigo de Jehova','Adventista','Evangelico','Otro','Ninguno')),
    phone VARCHAR2(15),
    responsible_person VARCHAR2(100),
    emergency_phone VARCHAR2(15),
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_patient_id_address FOREIGN KEY (id_address) REFERENCES addresses(id_address),
    CONSTRAINT fk_patient_id_birth_city FOREIGN KEY (id_birth_city) REFERENCES cities(id_city)
) TABLESPACE shce_datos;

-- Crear tabla de usuarios del sistema
CREATE TABLE users (
    id_user NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area NUMBER NOT NULL,
    id_address NUMBER NOT NULL,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(50) NOT NULL,
    paternal_surname VARCHAR2(25) NOT NULL,
    maternal_surname VARCHAR2(25) NOT NULL,
    email VARCHAR2(150) UNIQUE,
    phone VARCHAR2(16),
    enabled CHAR(1) DEFAULT '1' CHECK (enabled IN ('0','1')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_users_id_area FOREIGN KEY (id_area) REFERENCES areas(id_area),
    CONSTRAINT fk_users_id_address FOREIGN KEY (id_address) REFERENCES addresses(id_address)
) TABLESPACE shce_datos;

-- Crear tabla de medicamentos
CREATE TABLE medicament (
    id_medicament NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_active_ingredient NUMBER NOT NULL,
    id_presentation NUMBER NOT NULL,
    id_route NUMBER NOT NULL,
    concentration VARCHAR2(50) NOT NULL,
    enabled CHAR(1) DEFAULT '1' CHECK (enabled IN ('0','1')) NOT NULL,
    CONSTRAINT fk_medicament_id_active_ingredient FOREIGN KEY (id_active_ingredient)
        REFERENCES active_ingredient(id_active_ingredient),
    CONSTRAINT fk_medicament_id_presentation FOREIGN KEY (id_presentation)
        REFERENCES presentation(id_presentation),
    CONSTRAINT fk_medicament_id_route FOREIGN KEY (id_route)
        REFERENCES route(id_route)
) TABLESPACE shce_datos;

-- Crear tabla de tickets de atencion
CREATE TABLE ticket (
    id_ticket NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_patient NUMBER NOT NULL,
    ticket_number NUMBER(3) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ticket_id_patient FOREIGN KEY (id_patient)
        REFERENCES patient(id_patient)
) TABLESPACE shce_datos;

-- Crear tabla de historia familiar
CREATE TABLE familiar_history (
    id_patient_history NUMBER NOT NULL,
    id_familiar NUMBER NOT NULL,
    state VARCHAR2(10) NOT NULL CHECK (state IN ('No tiene','Vivo','Fallecido')),
    observations VARCHAR2(150),
    CONSTRAINT ck_familiar_history_obs CHECK (
        state = 'No tiene' OR (state IN ('Vivo','Fallecido') AND observations IS NOT NULL)
    ),
    CONSTRAINT pk_familiar_history PRIMARY KEY (id_patient_history, id_familiar),
    CONSTRAINT fk_familiar_history_id_familiar FOREIGN KEY (id_familiar)
        REFERENCES familiar(id_familiar),
    CONSTRAINT fk_familiar_history_id_patient_history FOREIGN KEY (id_patient_history)
        REFERENCES patient_history(id_patient_history)
) TABLESPACE shce_datos;

-- Crear tabla de habitos generales
CREATE TABLE general_history_habit (
    id_general_history NUMBER NOT NULL,
    id_habit NUMBER NOT NULL,
    has CHAR(1) CHECK (has IN ('0','1')) NOT NULL,
    frequency VARCHAR2(30),
    CONSTRAINT ck_general_history_freq CHECK (
        has = '0' OR (has = '1' AND frequency IS NOT NULL)
    ),
    CONSTRAINT pk_general_history_habit PRIMARY KEY (id_general_history, id_habit),
    CONSTRAINT fk_general_history_habit_id_habit FOREIGN KEY (id_habit)
        REFERENCES habit(id_habit),
    CONSTRAINT fk_general_history_habit_id_general_history FOREIGN KEY (id_general_history)
        REFERENCES general_history(id_general_history)
) TABLESPACE shce_datos;

-- Crear tabla de enfermedades en antecedentes patologicos
CREATE TABLE pathological_history_disease (
    id_pathological_history NUMBER NOT NULL,
    id_disease NUMBER NOT NULL,
    duration VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_pathological_history_disease PRIMARY KEY (id_pathological_history, id_disease),
    CONSTRAINT fk_phd_id_pathological_history FOREIGN KEY (id_pathological_history)
        REFERENCES pathological_history(id_pathological_history),
    CONSTRAINT fk_phd_id_disease FOREIGN KEY (id_disease)
        REFERENCES disease(id_disease)
) TABLESPACE shce_datos;

-- Crear tabla de ingredientes activos en medicamentos
CREATE TABLE active_ingredient_medicament (
    id_active_ingredient NUMBER NOT NULL,
    id_medicament NUMBER NOT NULL,
    CONSTRAINT pk_active_ing_med PRIMARY KEY (id_active_ingredient, id_medicament),
    CONSTRAINT fk_aim_id_active_ingredient FOREIGN KEY (id_active_ingredient)
        REFERENCES active_ingredient(id_active_ingredient),
    CONSTRAINT fk_aim_id_medicament FOREIGN KEY (id_medicament)
        REFERENCES medicament(id_medicament)
) TABLESPACE shce_datos;

-- Crear tabla de relaciones patologicas y reacciones adversas medicamentosas
CREATE TABLE ram (
    id_pathological_history NUMBER NOT NULL,
    id_active_ingredient NUMBER NOT NULL,
    CONSTRAINT pk_ram PRIMARY KEY (id_pathological_history, id_active_ingredient),
    CONSTRAINT fk_ram_id_pathological_history FOREIGN KEY (id_pathological_history)
        REFERENCES pathological_history(id_pathological_history),
    CONSTRAINT fk_ram_id_active_ingredient FOREIGN KEY (id_active_ingredient)
        REFERENCES active_ingredient(id_active_ingredient)
) TABLESPACE shce_datos;

-- Crear tabla de consultas medicas
CREATE TABLE consultation (
    id_consultation NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_doctor NUMBER NOT NULL,
    id_patient NUMBER NOT NULL,
    id_area NUMBER NOT NULL,
    responsible_name VARCHAR2(100),
    history_number VARCHAR2(15) NOT NULL,
    anamnesis CLOB NOT NULL,
    eva NUMBER(2) CHECK (eva BETWEEN 0 AND 10),
    physical_exam CLOB NOT NULL,
    management_plan CLOB NOT NULL,
    observations CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_consultation_id_doctor FOREIGN KEY (id_doctor)
        REFERENCES users(id_user),
    CONSTRAINT fk_consultation_id_patient FOREIGN KEY (id_patient)
        REFERENCES patient(id_patient),
    CONSTRAINT fk_consultation_id_area FOREIGN KEY (id_area)
        REFERENCES areas(id_area)
) TABLESPACE shce_datos;

-- Crear tabla de signos vitales
CREATE TABLE vital_signs (
    id_vital_signs NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_patient NUMBER NOT NULL,
    id_consultation NUMBER NOT NULL,
    height NUMBER(5,2),
    weight NUMBER(6,2),
    abdominal_perimeter NUMBER(3),
    systolic_blood_pressure NUMBER(3),
    diastolic_blood_pressure NUMBER(3),
    heart_rate NUMBER(3),
    oxygen_saturation NUMBER(3),
    temperature NUMBER(4,1),
    respiratory_rate NUMBER(3),
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vital_signs_id_patient FOREIGN KEY (id_patient)
        REFERENCES patient(id_patient),
    CONSTRAINT fk_vital_signs_id_consultation FOREIGN KEY (id_consultation)
        REFERENCES consultation(id_consultation)
) TABLESPACE shce_datos;

-- Crear tabla de derivaciones (referrals)
CREATE TABLE referral (
    id_referral NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consultation NUMBER NOT NULL,
    id_area NUMBER NOT NULL,
    CONSTRAINT fk_referral_id_consultation FOREIGN KEY (id_consultation)
        REFERENCES consultation(id_consultation),
    CONSTRAINT fk_referral_id_area FOREIGN KEY (id_area)
        REFERENCES areas(id_area)
) TABLESPACE shce_datos;

-- Crear tabla de diagnosticos asociados a derivaciones
CREATE TABLE referral_diagnosis (
    id_referral NUMBER NOT NULL,
    id_disease NUMBER NOT NULL,
    type VARCHAR2(15) NOT NULL CHECK (type IN ('PRESUNTIVO', 'DEFINITIVO')),
    observations VARCHAR2(200),
    CONSTRAINT pk_referral_diagnosis PRIMARY KEY (id_referral, id_disease),
    CONSTRAINT fk_ref_diag_id_referral FOREIGN KEY (id_referral)
        REFERENCES referral(id_referral),
    CONSTRAINT fk_ref_diag_id_disease FOREIGN KEY (id_disease)
        REFERENCES disease(id_disease)
) TABLESPACE shce_datos;

-- Crear tabla de diagnosticos de una consulta
CREATE TABLE diagnosis (
    id_diagnosis NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consultation NUMBER NOT NULL,
    id_disease NUMBER NOT NULL,
    type VARCHAR2(15) NOT NULL CHECK (type IN ('PRESUNTIVO', 'DEFINITIVO')),
    CONSTRAINT fk_diagnosis_id_consultation FOREIGN KEY (id_consultation)
        REFERENCES consultation(id_consultation),
    CONSTRAINT fk_diagnosis_id_disease FOREIGN KEY (id_disease)
        REFERENCES disease(id_disease)
) TABLESPACE shce_datos;

-- Crear tabla de medicamentos asociados a diagnosticos
CREATE TABLE diagnosis_medicament (
    id_diagnosis NUMBER NOT NULL,
    id_medicament NUMBER NOT NULL,
    quantity NUMBER(3) NOT NULL,
    instructions VARCHAR2(150) NOT NULL,
    duration VARCHAR2(25) NOT NULL,
    CONSTRAINT pk_diag_med PRIMARY KEY (id_diagnosis, id_medicament),
    CONSTRAINT fk_diag_med_id_diagnosis FOREIGN KEY (id_diagnosis)
        REFERENCES diagnosis(id_diagnosis),
    CONSTRAINT fk_diag_med_id_medicament FOREIGN KEY (id_medicament)
        REFERENCES medicament(id_medicament)
) TABLESPACE shce_datos;

-- Crear tabla de areas por ticket (flujo de atencion)
CREATE TABLE ticket_area (
    id_ticket NUMBER NOT NULL,
    id_area NUMBER NOT NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP,
    state VARCHAR2(15) NOT NULL CHECK (state IN ('EN ATENCION','EN ESPERA','ATENDIDO')),
    CONSTRAINT pk_ticket_area PRIMARY KEY (id_ticket, id_area),
    CONSTRAINT fk_ticket_area_id_ticket FOREIGN KEY (id_ticket)
        REFERENCES ticket(id_ticket),
    CONSTRAINT fk_ticket_area_id_area FOREIGN KEY (id_area)
        REFERENCES areas(id_area)
) TABLESPACE shce_datos;


-- INDICES 

-- Areas
CREATE INDEX idx_areas_id_role ON areas(id_role) TABLESPACE shce_datos;

-- Users
CREATE INDEX idx_users_id_area ON users(id_area) TABLESPACE shce_datos;

-- Geografia
CREATE INDEX idx_regions_id_country      ON regions(id_country)      TABLESPACE shce_datos;
CREATE INDEX idx_provinces_id_region     ON provinces(id_region)     TABLESPACE shce_datos;
CREATE INDEX idx_cities_id_province      ON cities(id_province)      TABLESPACE shce_datos;
CREATE INDEX idx_addresses_id_city       ON addresses(id_city)       TABLESPACE shce_datos;

-- Pacientes y usuarios
CREATE INDEX idx_patient_id_address      ON patient(id_address)      TABLESPACE shce_datos;
CREATE INDEX idx_patient_id_birth_city   ON patient(id_birth_city)   TABLESPACE shce_datos;
CREATE INDEX idx_users_id_address        ON users(id_address)        TABLESPACE shce_datos;

-- Consultas y signos
CREATE INDEX idx_consultation_patient    ON consultation(id_patient) TABLESPACE shce_datos;
CREATE INDEX idx_consultation_doctor     ON consultation(id_doctor)  TABLESPACE shce_datos;
CREATE INDEX idx_consultation_area       ON consultation(id_area)    TABLESPACE shce_datos;
CREATE INDEX idx_consultation_created    ON consultation(created_at) TABLESPACE shce_datos;

CREATE INDEX idx_vitals_consultation     ON vital_signs(id_consultation) TABLESPACE shce_datos;
CREATE INDEX idx_vitals_patient          ON vital_signs(id_patient)      TABLESPACE shce_datos;

-- Tickets
CREATE INDEX idx_ticket_id_patient       ON ticket(id_patient)       TABLESPACE shce_datos;
CREATE INDEX idx_ticketarea_id_ticket    ON ticket_area(id_ticket)   TABLESPACE shce_datos;
CREATE INDEX idx_ticketarea_state        ON ticket_area(state)       TABLESPACE shce_datos;

-- Farmacos
CREATE INDEX idx_medicament_ai           ON medicament(id_active_ingredient) TABLESPACE shce_datos;
CREATE INDEX idx_medicament_presentation ON medicament(id_presentation)      TABLESPACE shce_datos;
CREATE INDEX idx_medicament_route        ON medicament(id_route)             TABLESPACE shce_datos;

-- Tablas puente
CREATE INDEX idx_aim_medicament          ON active_ingredient_medicament(id_medicament) TABLESPACE shce_datos;
CREATE INDEX idx_phd_disease             ON pathological_history_disease(id_disease)    TABLESPACE shce_datos;
CREATE INDEX idx_ram_active_ingredient   ON ram(id_active_ingredient)                   TABLESPACE shce_datos;

-- Historiales
CREATE INDEX idx_famhist_patienthist     ON familiar_history(id_patient_history) TABLESPACE shce_datos;
CREATE INDEX idx_ghh_generalhistory      ON general_history_habit(id_general_history) TABLESPACE shce_datos;

-- Diagnosticos
CREATE INDEX idx_diagnosis_consultation  ON diagnosis(id_consultation) TABLESPACE shce_datos;
CREATE INDEX idx_diagnosis_disease       ON diagnosis(id_disease)      TABLESPACE shce_datos;
CREATE INDEX idx_diagmed_medicament      ON diagnosis_medicament(id_medicament) TABLESPACE shce_datos;

-- Derivaciones
CREATE INDEX idx_referral_consultation   ON referral(id_consultation) TABLESPACE shce_datos;
CREATE INDEX idx_refdiag_disease         ON referral_diagnosis(id_disease) TABLESPACE shce_datos;



-- VISTAS

-- 1) Detalle de usuario con su area y rol
CREATE OR REPLACE VIEW v_user_detail AS
SELECT
  u.id_user,
  u.username,
  u.email,
  u.enabled,
  u.name       AS user_name,
  u.paternal_surname,
  u.maternal_surname,
  a.id_area,
  a.name       AS area_name,
  r.id_role,
  r.name       AS role_name,
  u.created_at,
  u.updated_at
FROM users u
JOIN areas a ON a.id_area = u.id_area
JOIN roles r ON r.id_role = a.id_role;

-- 2) Detalle de paciente con direccion y ciudad
CREATE OR REPLACE VIEW v_patient_contact AS
SELECT
  p.id_patient,
  p.name,
  p.paternal_surname,
  p.maternal_surname,
  p.document_type,
  p.document_number,
  p.phone,
  p.emergency_phone,
  a.street,
  a.reference,
  c.name AS city_name
FROM patient p
JOIN addresses a ON a.id_address = p.id_address
JOIN cities c     ON c.id_city     = a.id_city;

-- 3) Ciudades con provincia, region y pais
CREATE OR REPLACE VIEW v_city_hierarchy AS
SELECT
  c.id_city,
  c.name          AS city_name,
  p.name          AS province_name,
  r.name          AS region_name,
  co.name         AS country_name,
  co.iso_code
FROM cities c
JOIN provinces p ON p.id_province = c.id_province
JOIN regions   r ON r.id_region   = p.id_region
JOIN countries co ON co.id_country = r.id_country;

-- 4) Conteo de consultas por area y dia 
CREATE MATERIALIZED VIEW mv_consultation_daily_area
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
  a.id_area,
  a.name          AS area_name,
  TRUNC(c.created_at) AS day_date,
  COUNT(*)        AS total_consultations
FROM consultation c
JOIN areas a ON a.id_area = c.id_area
GROUP BY a.id_area, a.name, TRUNC(c.created_at);
